### ISSUE TITLE
Why not have a parameterless constructore validation at compile time?

### ISSUE THREAD

**Issue by weitzhandler** [matthewschrager/Repository#1]
Hi I'm just looking at the EFRepository, and I see you throw an exception if the DbContext doesn't have a parameterless constructor, I'm wondering since you can do it all at compile time using the 'new' constraint, example:

public class Repository<TContext> where TContext : DbContext, new()
{
}

Check it out: http://goo.gl/Q78AP

**Comment by weitzhandler** [comment]
OOPS my bad, I didn't even read the code carefully enough :-1: 

I didn't notice the context factory thingy, yeah, that's surely the efficient way.

**Comment by matthewschrager** [comment]
No problem, thanks for the input :)
